name: Merge base branch into PRs

on:
  push:
    branches:
      - master

jobs:
  merge:
    name: PR base merge
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - name: PR base merge
      uses: deliveryhero/pr-base-auto-merger@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_DELAY: 5
        MERGE_LABEL: 'enqueue'
